services:
  api:
    image: stable-diffusion-api:latest
    ports:
      - 7860:7860
    container_name: stable-diffusion-api
    volumes:
      - ./models/:/stable-diffusion/models
      - ./configs/:/stable-diffusion/configs
      - ./outputs:/stable-diffusion/outputs
      - ./extensions:/stable-diffusion/extensions
      - ./modules/:/stable-diffusion/modules
      - ./get_models.sh:/stable-diffusion/get_models.sh:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
     resources:
       reservations:
         devices:
           - capabilities: [gpu]
    runtime: nvidia
    networks:
      - mynetwork
    command: ["python3", "launch.py", "--listen", "--api"]
    stdin_open: true
    tty: true
networks:
  mynetwork:
    driver: bridge