services:
  api:
    build:
      context: ./
    image: automatic1111-stable-diffusion:latest
    ports:
      - 7860:7860
    container_name: stable-diffusion-api
    volumes:
      - ./models/:/stable-diffusion/models
      - ./configs/:/stable-diffusion/configs
      - ./outputs:/stable-diffusion/outputs
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
     resources:
       reservations:
         devices:
           - capabilities: [gpu]
    runtime: nvidia
    networks:
      - mynetwork
    command: ["python3", "launch.py", "--listen", "--api"]
    stdin_open: true
    tty: true
networks:
  mynetwork:
    driver: bridge